name: 1.0.$(Rev:r)

trigger:
- master

pr:
  - master
  - development

stages:
  - stage: Build
    variables:
      - group: pulumi-access-token
    jobs: 
      - job: Preview

        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - checkout: self
            fetchDepth: 1

          - task: Pulumi@1
            displayName: 'Preview Infrastructure Changes'
            condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual'))
            inputs:
              azureSubscription: 'Azure - Personal'
              command: 'preview'
              args: '--diff --refresh --non-interactive'
              cwd: 'pulumi-devops-pipeline/stack'
              stack: 'jamesrcounts/AzureCSharp.DevOpsPipeline/azcs-devopspipeline-dev'
